### ISSUE TITLE
Move from jscs to ESLint?

### ISSUE THREAD

**Issue by yan12125** [mozilla-jetpack/jpm#571]
JSCS is declared to be deprecated and merged into ESLint: https://github.com/jscs-dev/node-jscs. I haven't tried ESLint, though.

**Comment by freaktechnik** [comment]
I've tried to convert the jshint and jscs configs to elsint in https://github.com/freaktechnik/jpm/commit/c0ef0aa7a49aff52d4deaf3c202534256f686a8d, however the current `eslint-config-google` is stricter than the actual google style guide, and thus a lot of errors are found (105 errors) just in `lib`.

I was able to make the config for tests work like the old one did, however that was way easier since there are no style checks for the tests.

**Comment by yan12125** [comment]
Lots of new errors looks good guidelines for me, while some may be too strict for jpm. Among them I guess ```comma-dangle``` and ```dot-location``` can be disabled.

**Comment by freaktechnik** [comment]
As a side note, switching to eslint would remove a source of outdated minimatch, though that is of course only in the devDependencies, so not that important either way.

**Comment by pdehaan** [comment]
I took a rough stab at this, but I think it needs more time than I can spend on it.

I did my best to convert the sparse .jshintrc and .jscsrc into an .eslintrc.yml using [**polyjuice**](http://npm.im/polyjuice), and then started doing some fine tuning:

### .eslintrc.yml
```yml
env:
  node: true

extends: eslint:recommended

root: true

rules:
  array-bracket-spacing: [2, never, {singleValue: true}]
  brace-style: 0 # TODO: Set to 1|2?
  camelcase: [2, {properties: always}]
  comma-dangle: 0 # TODO: Set to `[2, always|never]`?
  curly: 0 # TODO: Set to 1|2?
  dot-notation: 2
  eol-last: 2
  indent: [2, 2, {SwitchCase: 1}]
  key-spacing: [2, {beforeColon: false, afterColon: true}]
  max-len: [0, 80] # TODO: Set to 1|2?
  new-cap: 2
  no-console: 0 # TODO: Set to 1|2?
  no-mixed-spaces-and-tabs: 2
  no-multi-str: 2
  no-multiple-empty-lines: 2
  no-spaced-func: 2
  no-trailing-spaces: 2
  no-unused-vars: [2, {vars: all, args: none}]
  no-with: 2
  one-var: [2, never]
  operator-linebreak: [2, after]
  quotes: [2, double]
  semi: [2, always]
  space-before-blocks: [2, always]
  space-before-function-paren: [2, never]
  space-in-parens: [2, never]
  space-infix-ops: 2
  space-return-throw-case: 0
  space-unary-ops: 0
```

### .eslintignore

```yml
test/addons
test/addon_runners
test/fixtures
```

### test/.eslintrc.yml

```yml
env:
  mocha: true

rules:
  max-len: 0
```

After a bit of fiddling with autofixing rules (via `$ eslint bin/jpm lib test --fix`), I got it down to 48 errors (37 of which are `no-unused-vars` violations). The 11 remaining errors seem superficially trivial and may just require code changes, or rule tweaking.
